language: java
jdk:
  - openjdk8

branches:
  only:
    - master

#Travis Server Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$home/.gradle'

script: "./gradlew clean build"

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: stackunderflow-deploy-s3 # 6-3-3에서 생성한 S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    on:
      repo: betterfly88/stackunderflow
      branch: master


#when CI completed send mail
notifications:
  email:
    recipients:
      - betterfly4202@gmail.com